//! Vortex-Ai-Chat browser UI (Leptos CSR → WebAssembly).
//! All application logic runs as Rust compiled to WASM; the only "JS" is the
//! wasm-bindgen glue generated by the Rust toolchain.

pub mod api;
pub mod chat;
pub mod markdown;
pub mod settings_ui;
pub mod sidebar;
pub mod sse;
pub mod state;
pub mod tasks;

use crate::sidebar::Sidebar;
use leptos::prelude::*;
use leptos::task::spawn_local;
use state::{AppCtx, Tab};

#[component]
pub fn App() -> impl IntoView {
    let ctx = AppCtx::new();
    provide_context(ctx.clone());

    // Load settings + capabilities first (drives theme + honest state).
    let ctx_boot = ctx.clone();
    spawn_local(async move {
        match api::settings().await {
            Ok(s) => {
                crate::state::apply_theme(s.theme);
                ctx_boot.settings.set(Some(s));
            }
            Err(e) => ctx_boot
                .error_banner
                .set(Some(format!("could not load settings: {e}"))),
        }
        match api::health().await {
            Ok(c) => ctx_boot.capabilities.set(Some(c)),
            Err(e) => ctx_boot
                .error_banner
                .set(Some(format!("server unreachable: {e}"))),
        }
        if let Ok(convs) = api::conversations("").await {
            ctx_boot.conversations.set(convs);
        }
        if let Ok(apprs) = api::approvals().await {
            ctx_boot.approvals.set(apprs);
        }
    });

    // Poll pending approvals so requests raised by sub-agents appear promptly.
    let ctx_poll = ctx.clone();
    set_interval(
        move || {
            let ctx = ctx_poll.clone();
            spawn_local(async move {
                if let Ok(apprs) = api::approvals().await {
                    ctx.approvals.set(apprs);
                }
            });
        },
        std::time::Duration::from_secs(5),
    );

    view! {
        <div class="app">
            <Sidebar />
            <main class="main">
                <header class="topbar">
                    <div class="tabs" role="tablist">
                        <button class=tab_class(ctx.clone(), Tab::Chat)
                            on:click=move |_| ctx.tab.set(Tab::Chat)>"Chat"</button>
                        <button class=tab_class(ctx.clone(), Tab::Tasks)
                            on:click=move |_| ctx.tab.set(Tab::Tasks)>
                            {move || {
                                let pending = ctx.approvals.get().len();
                                if pending > 0 { format!("Tasks ({pending})") } else { "Tasks".to_string() }
                            }}
                        </button>
                        <button class=tab_class(ctx.clone(), Tab::Settings)
                            on:click=move |_| ctx.tab.set(Tab::Settings)>"Settings"</button>
                    </div>
                    <div class="mode-select" title="Tools available to the assistant for the next message">
                        <label for="mode">"Mode"</label>
                        <select id="mode" on:change=move |ev| {
                            let v = event_target_value(&ev);
                            if let Ok(m) = serde_json::from_value::<vortex_types::Mode>(
                                serde_json::Value::String(v),
                            ) {
                                ctx.mode.set(m);
                            }
                        }>
                            {move || {
                                let m = ctx.mode.get();
                                view! {
                                    <option value="chat" selected={m == vortex_types::Mode::Chat}>"Chat"</option>
                                    <option value="research" selected={m == vortex_types::Mode::Research}>"Research"</option>
                                    <option value="coding" selected={m == vortex_types::Mode::Coding}>"Coding"</option>
                                    <option value="browser" selected={m == vortex_types::Mode::Browser}>"Browser"</option>
                                }
                            }}
                        </select>
                    </div>
                    <ThemeToggle />
                </header>
                <Show when=move || ctx.error_banner.get().is_some()>
                    <div class="banner error">
                        {move || ctx.error_banner.get().unwrap_or_default()}
                    </div>
                </Show>
                <div class="content">
                    {move || match ctx.tab.get() {
                        Tab::Chat => view! { <chat::ChatView /> }.into_any(),
                        Tab::Tasks => view! { <tasks::TasksView /> }.into_any(),
                        Tab::Settings => view! { <settings_ui::SettingsView /> }.into_any(),
                    }}
                </div>
            </main>
            <Show when=move || ctx.toast.get().is_some()>
                <div class="toast" role="status">{move || ctx.toast.get().unwrap_or_default()}</div>
            </Show>
        </div>
    }
}

fn tab_class(ctx: AppCtx, tab: Tab) -> impl Fn() -> String + Clone {
    move || {
        if ctx.tab.get() == tab {
            "tab active".to_string()
        } else {
            "tab".to_string()
        }
    }
}

#[component]
fn ThemeToggle() -> impl IntoView {
    let ctx = use_context::<AppCtx>().expect("ctx provided");
    view! {
        <button class="icon-btn"
            title="Toggle theme"
            on:click=move |_| {
                let s = ctx.settings.get_untracked();
                let new_theme = match s.as_ref().map(|s| s.theme) {
                    Some(vortex_types::Theme::Light) => vortex_types::Theme::Dark,
                    _ => vortex_types::Theme::Light,
                };
                crate::state::apply_theme(new_theme);
                if let Some(mut s) = s {
                    s.theme = new_theme;
                    let ctx = ctx.clone();
                    spawn_local(async move {
                        if let Ok(saved) = api::save_settings(&s).await {
                            ctx.settings.set(Some(saved));
                        }
                    });
                }
            }>
            {move || {
                match ctx.settings.get().map(|s| s.theme) {
                    Some(vortex_types::Theme::Light) => "☾".to_string(),
                    _ => "☀".to_string(),
                }
            }}
        </button>
    }
}
